@startuml
class Competicion {
    + Id : int <<get>> <<set>>
    + Plazas : int <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + Competicion()
    + Competicion(id:int, fecha:DateTime, lugar:String, nombre:String, plazas:int, precio:decimal)
    + <<override>> Equals(otro:object?) : bool
    + <<override>> GetHashCode() : int
}
class "ICollection`1"<T> {
}
Competicion --> "Fecha" DateTime
Competicion --> "Lugar" String
Competicion --> "Nombre" String
Competicion --> "TipoDeporte" TipoDeporte
Competicion o-> "CompeticionInscripciones<CompeticionInscripcion>" "ICollection`1"
@enduml
