@startuml
class Reserva {
    + Id : int <<get>> <<set>>
    + <<required>> NombreCliente : string <<get>> <<set>>
    + <<required>> Apellidos : string <<get>> <<set>>
    + <<required>> Dni : string <<get>> <<set>>
    + <<required>> FechaReserva : DateTime <<get>> <<set>>
    + <<required>> MetodoPago : MetodoPago <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + PistasReservadas : ICollection<PistaReservada> <<get>> <<set>>
    + Reserva()
    + Reserva(id:int, nombreCliente:string, apellidos:string, dni:string, fechaReserva:DateTime, metodoPago:MetodoPago, precioTotal:decimal)
    + <<override>> Equals(otro:object?) : bool
    + <<override>> GetHashCode() : int
}
class "ICollection`1"<T> {
}
Reserva --> "FechaReserva" DateTime
Reserva --> "MetodoPago" MetodoPago
Reserva o-> "PistasReservadas<PistaReservada>" "ICollection`1"
@enduml
