@startuml
class TipoMaterial {
    + IdTipoMaterial : int <<get>> <<set>>
    + <<required>> NombreTipoMaterial : string <<get>> <<set>>
    + Materiales : ICollection<Material> <<get>> <<set>>
    + TipoMaterial()
    + TipoMaterial(idTipoMaterial:int, nombreTipoMaterial:string)
    + <<override>> Equals(otro:object?) : bool
    + <<override>> GetHashCode() : int
}
@enduml
