@startuml
class TipoMaterial {
    + IdTipoMaterial : int <<get>> <<set>>
    + <<required>> NombreTipoMaterial : string <<get>> <<set>>
    + TipoMaterial()
    + TipoMaterial(idTipoMaterial:int, nombreTipoMaterial:string)
    + <<override>> Equals(otro:object?) : bool
    + <<override>> GetHashCode() : int
}
class "ICollection`1"<T> {
}
TipoMaterial o-> "Materiales<Material>" "ICollection`1"
@enduml
